<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="POU_Test" Id="{196e0b9a-9deb-4dd0-a48f-8902bcc60beb}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU_Test
VAR
	fbSimpleLinearTwoWayDriveTest: FB_SimpleLinearTwoWayDrive_Test; 
	fbLinearMovementWithFeedbackTest: FB_LinearMovementWithFeedbackTest;
	fbSewMovitracBFieldbusTest: FB_SewMovitracBFieldbusTest;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
    <LineIds Name="POU_Test">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>