<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_SimpleRotaryTwoWayDrive" Id="{91ccde8e-c8b2-4c10-8627-24b2c55efbe7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SimpleRotaryTwoWayDrive EXTENDS FB_Unit
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_SimpleRotaryTwoWayDrive">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>